services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./setup/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./setup/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: acerto
      MYSQL_USER: db_acerto
      MYSQL_PASSWORD: db_acerto_pass
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata: