services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./setup/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./setup/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./setup/mysql:/docker-entrypoint-initdb.d/
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 9255:80
